import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { User } from '../../users/user.entity';
import { Chart } from './chart.entity';

/**
 * Issued when a run starts, spent when it is submitted.
 *
 * This row is what makes "token reused" detectable. Without it a single valid
 * submission could be replayed for coins indefinitely, and no amount of
 * scoring rigour upstream would notice.
 */
@Entity('game_run_tokens')
@Index('IDX_game_run_tokens_expiresAt', ['expiresAt'])
export class RunToken {
  /** Client-visible run token; generated by the server, never by the client. */
  @PrimaryColumn('uuid')
  id: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: User;

  @Column('uuid')
  userId: string;

  @ManyToOne(() => Chart, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'chartId' })
  chart: Chart;

  @Column('uuid')
  chartId: string;

  /** Pinned at issue time, so a chart edited mid-run invalidates the token. */
  @Column({ type: 'varchar', length: 64 })
  chartHash: string;

  @Column({ default: false })
  practiceMode: boolean;

  @CreateDateColumn({ type: 'timestamptz' })
  issuedAt: Date;

  @Column({ type: 'timestamptz' })
  expiresAt: Date;

  @Column({ type: 'timestamptz', nullable: true })
  consumedAt: Date | null;
}
