/**
 * The Cloudflare entry point: a tester gate in front of the Next app.
 *
 * When GATE_USER + GATE_PASSWORD are set (as Worker secrets), every page
 * request must pass HTTP Basic Auth once; success drops a cookie so client
 * navigations are not re-challenged. Unset, this is a pass-through.
 *
 * It lives here rather than in `src/proxy.ts` because Next 16 runs Proxy on
 * the Node.js runtime only, and OpenNext's support for that on Cloudflare is
 * experimental. A wrapper Worker is the adapter's documented pattern and
 * keeps the gate out of the app — local `npm run dev` never sees it.
 *
 * Same shape as the shop's staging gate (`frontend/src/proxy.ts`). It keeps
 * the game out of public view while it is being tried; it is not access
 * control over data — the API has its own sessions. No conflict with the
 * game's sign-in either: its Bearer token goes to the API origin, not here.
 */

// Generated by `opennextjs-cloudflare build`.
import { default as handler } from "../.open-next/worker.js";

interface GateEnv {
  GATE_USER?: string;
  GATE_PASSWORD?: string;
}

const AUTH_COOKIE = "stiff_game_gate";

async function expectedToken(user: string, password: string): Promise<string> {
  const data = new TextEncoder().encode(`${user}:${password}:stiff-game-gate`);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function readCookie(request: Request, name: string): string | null {
  const header = request.headers.get("cookie");
  if (!header) return null;
  for (const part of header.split(";")) {
    const [key, ...rest] = part.trim().split("=");
    if (key === name) return rest.join("=");
  }
  return null;
}

function credentialsMatch(request: Request, user: string, password: string): boolean {
  const header = request.headers.get("authorization");
  if (!header?.startsWith("Basic ")) return false;
  try {
    const decoded = atob(header.slice(6));
    const split = decoded.indexOf(":");
    return (
      split > 0 &&
      decoded.slice(0, split) === user &&
      decoded.slice(split + 1) === password
    );
  } catch {
    return false; // malformed header
  }
}

export default {
  async fetch(request: Request, env: GateEnv, ctx: ExecutionContext): Promise<Response> {
    const user = env.GATE_USER;
    const password = env.GATE_PASSWORD;
    if (!user || !password) return handler.fetch(request, env, ctx);

    const token = await expectedToken(user, password);
    if (readCookie(request, AUTH_COOKIE) === token) {
      return handler.fetch(request, env, ctx);
    }

    if (credentialsMatch(request, user, password)) {
      const response = await handler.fetch(request, env, ctx);
      const withCookie = new Response(response.body, response);
      const secure = new URL(request.url).protocol === "https:" ? "; Secure" : "";
      withCookie.headers.append(
        "Set-Cookie",
        // one login per browser per week
        `${AUTH_COOKIE}=${token}; Path=/; Max-Age=604800; HttpOnly; SameSite=Lax${secure}`,
      );
      return withCookie;
    }

    return new Response("Authentication required.", {
      status: 401,
      headers: { "WWW-Authenticate": 'Basic realm="STIFF game (testing)"' },
    });
  },
} satisfies ExportedHandler<GateEnv>;
